GET http://localhost:3000/events 

###
# @name createEvent
POST http://localhost:3000/events 
Content-Type: application/json

{
  "name": "Teste Evento",
  "description": "Testand novo evento",
  "date": "2024-03-03T02:00:00",
  "price": 25
}

###
@eventId = {{ createEvent.response.body.id }}

###
GET http://localhost:3000/events/{{eventId}}


###
PATCH http://localhost:3000/events/{{eventId}} 
Content-Type: application/json

{
  "name": "Teste Evento",
  "description": "Testand novo",
  "date": "2024-03-03T02:00:00",
  "price": 25
}

###
DELETE http://localhost:3000/events/{{eventId}}
